name: app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

  #Utility Packages
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1



  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  flutter_native_splash: ^2.4.5
  smooth_page_indicator: ^1.2.1

  #State Management
  get: ^4.6.5
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #Assets
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/on_boarding_images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

